name: Test GitHub AI Model

on:
  workflow_dispatch:  # allows manual triggering

permissions:
  models: read  # required for accessing GitHub Models API

jobs:
  test-model:
    runs-on: ubuntu-latest

    steps:
      - name: Call GitHub AI model
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s "https://models.github.ai/inference/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d '{
              "model": "openai/gpt-4o-mini",
              "messages": [
                {"role": "user", "content": "Count 1 to 20 in word for me"}
              ]
            }' | jq
