name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-openai:
           runs-on: ubuntu-latest
           steps:
             - name: Test OpenAI API
               env:
                 OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
               run: |
                 RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
                   -H "Authorization: Bearer $OPENAI_API_KEY" \
                   -H "Content-Type: application/json" \
                   -d '{
                     "model": "gpt-4o-mini",
                     "messages": [{"role": "user", "content": "Say hello world"}],
                     "max_tokens": 50
                   }')
                 if echo "$RESPONSE" | grep -q '"content":'; then
                   CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
                   echo "API key works! Response: $CONTENT"
                 else
                   echo "API call failed. Response: $RESPONSE"
                   exit 1
                 fi
  
             - name: Notify on failure
               if: failure()
               uses: actions/github-script@v7
               with:
                 script: |
                   github.rest.issues.createComment({
                     issue_number: context.issue.number,
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     body: 'Failed to verify OpenAI API key. Check logs.'
                   })
